version: '3.1'

services:
    result:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:alpine'
        volumes:
            - .db:/var/lib/postgresql/data
        env_file: backend/.env

    frontend:
        build:
            dockerfile: frontend/Dockerfile
            context: .
        volumes:
            - ./:/app/
        ports:
            - '3000:3000'

    backend:
        build:
            dockerfile: backend/Dockerfile
            context: .
        ports:
            - '8000:8000'
        volumes:
            - ./:/home/user/app/
        env_file: backend/.env
        depends_on:
            - result
            - frontend
