# Generated by Django 3.1.6 on 2021-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreTrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.TextField()),
                ('meta_data', models.TextField()),
            ],
        ),
    ]
