# Generated by Django 3.1.6 on 2021-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretrainingdata',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
