# Generated by Django 3.1.6 on 2021-03-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_requestrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_table', models.BooleanField()),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='requestrecord',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
